PROGRAM RUNFIRSTORSECONDPART
  IMPLICIT NONE
  INTEGER R136,MC,POT,RHO,SFE,SEG,SIMF,GEN,COL,NPARTALL,NPART,CONT,VIRF,SECONDSEG,SFES(2),SECONDRH,SECSEGH,FIMF !INITIOPTION
  REAL TCOL,TVIR,MCLUSTER,SX(10),MATTAB(2,5000),TEND,MCLUSTER2,SX2(10)
  CHARACTER*20 OPT(6),CLUSTERORI(10)
  CHARACTER*300 PATH,FILEPOT,SIMICHAR(3,10),PATH2(4),SFESCHAR(3),HOME2
  CHARACTER*300 FOLDER1,FOLDER2,FOLDER3,FOLDER4
  CHARACTER*30 SFERH
  
  INTEGER*4 chdir, n !folder
  INTEGER SIM,RUN !LOOPS
  INTEGER WGPU !AUX
  
  
  PRINT*,"FILE NAME= run1or2part.f90"
  CALL INITIOPTION(R136,MC,POT,RHO,SFE,SEG,SIMF,OPT,PATH,SIMICHAR,GEN,COL,TCOL,TVIR,MCLUSTER,&
       NPARTALL,SX,FILEPOT,MATTAB,TEND,CONT,VIRF,SECONDSEG,PATH2,SFES,SFESCHAR,MCLUSTER2,&
       SECONDRH,HOME2,SFERH,CLUSTERORI,SECSEGH,FIMF)
1 PRINT*,"WHICH GPU? compgpu6=1, HGPU=2"
  READ(*,*) WGPU
  IF(WGPU.LT.1.OR.WGPU.GT.2) GOTO 1
  !IF(GEN.EQ.2) CALL WAITINGFORRUNING(OPT,SFESCHAR)!(NSIM,MAXSIM,SIM)
  DO SIM=1,SIMF
     IF(GEN.EQ.2) THEN
        FOLDER1=TRIM(PATH)//TRIM(SIMICHAR(1,SIM))
        FOLDER2=TRIM(PATH)//TRIM(SIMICHAR(2,SIM))
        !IF(SECONDRH.EQ.0.AND.SECSEGH.EQ.0)
        FOLDER3=TRIM(PATH2(1))//TRIM(SIMICHAR(3,SIM))
        IF(SECONDRH.GT.0.OR.SECSEGH.GT.0.OR.FIMF.GT.0)THEN
             FOLDER3=TRIM(HOME2)//"cluster/"//TRIM(OPT(6))//"/"//TRIM(OPT(5))//"/"//TRIM(SFESCHAR(2))&
             //TRIM(SFERH)//TRIM(CLUSTERORI(SIM+5))
             FOLDER4=TRIM(HOME2)//"cluster/"//TRIM(OPT(6))//"/"//TRIM(OPT(5))//"/"//TRIM(SFESCHAR(2))&
                  //TRIM(SFERH)
          END IF
        CALL COPYFOLDER(FOLDER1,FOLDER2,VIRF,SECONDSEG,FOLDER3,SECONDRH,SECSEGH,FIMF,FOLDER4,SX2)
     END IF
     N = CHDIR(TRIM(PATH)//TRIM(SIMICHAR(GEN,SIM)))
     IF(N.NE.0) stop 'chdir: error'
     IF(GEN.EQ.2.AND.SECONDSEG.EQ.1.AND.SECONDRH.EQ.0.AND.SECSEGH.EQ.0.AND.FIMF.EQ.0) PRINT*,"COPYING ../2ndgen/cluster_M* TO ./"
     IF(GEN.EQ.2.AND.SECONDSEG.EQ.1.AND.SECONDRH.EQ.0.AND.SECSEGH.EQ.0.AND.FIMF.EQ.0) CALL SYSTEM("cp ../2ndgen/cluster_M* ./") !copy 2nd cluster file
     IF(GEN.EQ.1) CALL SYSTEM("cp ../../sim_base/* ./") !copy default files
     DO RUN=1,2 !1:TO GET SCALING FROM NBODY6(ONLY GEN=1),2:RUN SIM
        CALL CLEANFOLDER()
        IF(POT.EQ.1) THEN
           IF(GEN.EQ.1.OR.(GEN.EQ.2.AND.RUN.EQ.2)) CALL MODFILES(RUN,GEN,TCOL,TVIR,MCLUSTER,&
                NPARTALL,NPART,SX,SIM,OPT,FILEPOT,MATTAB,TEND,CONT,VIRF,SFES,SFESCHAR,MCLUSTER2,MC,SECONDRH,SX2)
           IF(RUN.EQ.1.AND.GEN.EQ.1) THEN
              IF(WGPU.EQ.1) CALL SYSTEM("nbody6++.avx.gpu.mpi_WF6 < input > output.txt")
              IF(WGPU.EQ.2) CALL SYSTEM("nbody6++.avx.gpu.mpi_WF < input > output.txt")
           END IF
           IF(RUN.EQ.2) PRINT*,"RUNNING SIM",SIM
           IF(RUN.EQ.2) THEN
              IF(WGPU.EQ.1) CALL SYSTEM("nbody6++.avx.gpu.mpi_WF6 < input > output.txt&")
              IF(WGPU.EQ.2) CALL SYSTEM("nbody6++.avx.gpu.mpi_WF < input > output.txt&")
           END IF
        END IF
     END DO
     PRINT*,""
  END DO
  

END PROGRAM RUNFIRSTORSECONDPART



SUBROUTINE SECONDGENOPTS(SEG,VIRF,SECONDSEG,SECONDRH,SECONDSEGHIGH,FIMF,SIMICHAR,SIMICHAREXTRA,SFERH)
  IMPLICIT NONE
  INTEGER SEG,VIRF,SECONDSEG,SECONDRH,SECONDSEGHIGH,FIMF
  CHARACTER*300 SIMICHAR(3,10),SIMICHAREXTRA(19,10) !+2 FOLDER SECOND
  CHARACTER*30 SFERH


  SFERH=""
31 PRINT*,"QVAR VARIATION? 1(AFTER COLLAPSE, Q_i=0.5), 2(BEFORE COLAPSE, Q_i=0.5)"
  PRINT*,"3 (AFTER COLLAPSE, Q_i=0.4), 4(AFTER COLLAPSE, Q_i=0.2), 5(AFTER COLLAPSE, Q_i=0.3),  6(AFTER COLLAPSE, Q_i=0.35)"
  READ(*,*) VIRF
  IF(VIRF.LT.1.OR.VIRF.GT.6) GOTO 31
  IF(VIRF.EQ.2) SIMICHAR(2,:)=SIMICHAREXTRA(1,:) !2ndgen-3
     
32 IF(SEG.EQ.2) THEN
     PRINT*,"2NDGEN WITH NOSEG?=1, SEG=2?"
     READ(*,*) SECONDSEG
     IF(SECONDSEG.LT.1.OR.SECONDSEG.GT.2) GOTO 32
     IF(SECONDSEG.EQ.2) SIMICHAR(2,:)=SIMICHAREXTRA(2,:) !2ndgen-4
  END IF
     
33 PRINT*,"2NDGEN WITH DEFAULT? = 0 R_HALF:1.3 PC"
  PRINT*,"R_HALF:1.0 PC? = 1"
  PRINT*,"R_HALF:2.0 PC = 2"
  PRINT*,"R_HALF:1.4 PC = 3"
  READ(*,*) SECONDRH
  IF(SECONDRH.LT.0.OR.SECONDRH.GT.3) GOTO 33
  IF(SECONDRH.EQ.0) SFERH = "-Rh1.3"
  IF(SECONDRH.EQ.1) SFERH = "-Rh1.0"
  IF(SECONDRH.EQ.2) SFERH = "-Rh2.0"
  IF(SECONDRH.EQ.3) SFERH = "-Rh1.4"
  
34   IF(SEG.EQ.1) THEN
        PRINT*,"2NDGEN WITH SEG=0.99?=1, NORMAL=0 (0.6)"
        READ(*,*) SECONDSEGHIGH
        IF(SECONDSEGHIGH.LT.0.OR.SECONDSEG.GT.1) GOTO 34
        IF(SECONDSEGHIGH.EQ.1) SFERH = TRIM(SFERH)//"-HIGHSEG"
     END IF
     
35   PRINT*,"NORMAL KROUPA CUT (MMIN=0.1) =0"
     PRINT*,"Kroupa=1 (MMIN=0.08)"
     PRINT*,"paper IMF=2(MMIN=1.0, MMID=3, SLOPE1=0.6, SLOPE2=-1)"
     PRINT*,"2NDGEN IMF?,LONG IMF=3 (MMAX=320)"
     READ(*,*) FIMF
     IF(FIMF.LT.0.OR.FIMF.GT.3) GOTO 35
     IF(FIMF.EQ.1) SFERH = TRIM(SFERH)//"-FULLIMF"
     IF(FIMF.EQ.2) SFERH = TRIM(SFERH)//"-paperIMF"
     IF(FIMF.EQ.3) SFERH = TRIM(SFERH)//"-300FULLIMF"


     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0) SIMICHAR(2,:)=SIMICHAREXTRA(3,:) !2ndgen-5
     IF(SECONDRH.EQ.0.AND.SECONDSEGHIGH.EQ.1.AND.FIMF.EQ.0) SIMICHAR(2,:)=SIMICHAREXTRA(4,:) !2ndgen-6
     IF(SECONDRH.EQ.0.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.1) SIMICHAR(2,:)=SIMICHAREXTRA(5,:) !2ndgen-7
     IF(SECONDRH.EQ.0.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.2) SIMICHAR(2,:)=SIMICHAREXTRA(6,:) !2ndgen-8
     IF(SECONDRH.EQ.0.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.3) SIMICHAR(2,:)=SIMICHAREXTRA(7,:) !2ndgen-9
     IF(SECONDRH.EQ.2.AND.SECONDSEGHIGH.EQ.1.AND.FIMF.EQ.0) SIMICHAR(2,:)=SIMICHAREXTRA(8,:) !2ndgen-10
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.1.AND.FIMF.EQ.0) SIMICHAR(2,:)=SIMICHAREXTRA(9,:) !2ndgen-11
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.1.AND.FIMF.EQ.1) SIMICHAR(2,:)=SIMICHAREXTRA(10,:) !2ndgen-12
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.1.AND.FIMF.EQ.3) SIMICHAR(2,:)=SIMICHAREXTRA(11,:) !2ndgen-13
     IF(SECONDRH.EQ.3.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0) SIMICHAR(2,:)=SIMICHAREXTRA(12,:) !2ndgen-14
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.3) SIMICHAR(2,:)=SIMICHAREXTRA(13,:) !2ndgen-15
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0.AND.VIRF.EQ.3) SIMICHAR(2,:)=SIMICHAREXTRA(14,:) !2ndgen-16
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.3.AND.VIRF.EQ.3) SIMICHAR(2,:)=SIMICHAREXTRA(15,:) !2ndgen-17
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0.AND.VIRF.EQ.4) SIMICHAR(2,:)=SIMICHAREXTRA(16,:) !2ndgen-18
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.3.AND.VIRF.EQ.4) SIMICHAR(2,:)=SIMICHAREXTRA(17,:) !2ndgen-19
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0.AND.VIRF.EQ.5) SIMICHAR(2,:)=SIMICHAREXTRA(18,:) !2ndgen-20
     IF(SECONDRH.EQ.1.AND.SECONDSEGHIGH.EQ.0.AND.FIMF.EQ.0.AND.VIRF.EQ.6) SIMICHAR(2,:)=SIMICHAREXTRA(19,:) !2ndgen-21
   END SUBROUTINE SECONDGENOPTS
         


SUBROUTINE MODFILES(RUN,GEN,TCOL,TVIR,MCLUSTER,NPARTALL,NPART,SX,SIM,&
     OPT,FILEPOT,MATTAB,TEND,CONT,VIRF,SFES,SFESCHAR,MCLUSTER2,MC,SECONDRH,SX2)
  IMPLICIT NONE
  INTEGER RUN,GEN,NPARTALL,NPART,SIM,CONT,VIRF,SFES(2),MC,SECONDRH
  REAL TCOL,TVIR,MCLUSTER,SX(10),MATTAB(2,5000),TEND,TVIR1,MCLUSTER2,SX2(10)
  CHARACTER*20 OPT(6),RHOICHAR,SFEICHAR,SXPREV
  INTEGER I,J !LOOPS
  CHARACTER*300 FILECLUSTER,FILECLUSTER2,MASSCHAR,DUMMY(10),NPCHAR,SXCHAR,MAVCHAR,FILEPOT,NPCHAR0,FREQCHAR,MASSCHAR2,SFESCHAR(3)
  REAL VSX,TSX,MAT(8,NPARTALL),MAT2(8,NPARTALL),MATSN1(3,NPARTALL),MATSN2(3,NPARTALL),FREQ,TALLF,TLASTF,DT
  INTEGER NPART1,NPART2,SN1,SN2,SN,NPART0,SNORI,FRAMES,CONT1,NFRAMES
  REAL MATSNALL(3,NPARTALL),CTEK,SHIFT
  
  IF(MCLUSTER.LT.10000) WRITE(MASSCHAR,13) INT(MCLUSTER)
  IF(MCLUSTER.GE.10000.AND.MCLUSTER.LT.100000) WRITE(MASSCHAR,14) INT(MCLUSTER)
  IF(MCLUSTER.GE.100000.AND.MCLUSTER.LT.1000000) WRITE(MASSCHAR,15) INT(MCLUSTER)
  FILECLUSTER="cluster_M"//TRIM(MASSCHAR)//".00_1.txt"
  IF(MC.EQ.4.OR.MC.EQ.5) THEN
     IF(MCLUSTER2.LT.10000) WRITE(MASSCHAR2,13) INT(MCLUSTER2)
     IF(MCLUSTER2.GE.10000.AND.MCLUSTER2.LT.100000) WRITE(MASSCHAR2,14) INT(MCLUSTER2)
     IF(MCLUSTER2.GE.100000.AND.MCLUSTER2.LT.1000000) WRITE(MASSCHAR2,15) INT(MCLUSTER2)
     FILECLUSTER2="cluster_M"//TRIM(MASSCHAR2)//".00_1.txt"
  END IF
  IF(RUN.EQ.1.AND.GEN.EQ.1) THEN
     OPEN(11,FILE=FILECLUSTER,STATUS="OLD")
     OPEN(12,FILE="dat.10",STATUS="REPLACE")
     READ(11,*) DUMMY(1)
     DO I=1,NPARTALL
        READ(11,*,END=111) MAT(1:7,I)
        MAT(8,I)=I
        WRITE(12,*) MAT(1:7,I)
     END DO
111  CLOSE(11)
     NPART=I-1
     IF(NPART.GE.NPARTALL-1) THEN
        PRINT*,"I AM PROBABLY SKIPPING PARTICLES, YOU SHOULD INCREASE NPARTALL"
        STOP
     END IF
     CALL CREATETABLE(MAT(:,1:NPART),NPART,MCLUSTER,MATTAB,GEN,TCOL,TEND,MATSN1,SN1,NPARTALL,1)
     IF(NPART.LT.1000)  WRITE(NPCHAR,12) NPART
     IF(NPART.GE.1000.AND.NPART.LT.10000) WRITE(NPCHAR,13) NPART
     IF(NPART.GE.10000.AND.NPART.LT.100000) WRITE(NPCHAR,14) NPART
     IF(NPART.GE.100000.AND.NPART.LT.1000000) WRITE(NPCHAR,15) NPART
     WRITE(SXCHAR,16) SX(SIM)
     WRITE(MAVCHAR,16) REAL(MCLUSTER/NPART)
     
     
     CALL SYSTEM("sed -i '1s/cltime/4.0/g' input")
     CALL SYSTEM("sed -i '2s/npart/"//TRIM(NPCHAR)//"/g' input")
     CALL SYSTEM("sed -i '3s/rscl/"//TRIM(SXCHAR)//"/g' input")
     CALL SYSTEM("sed -i '3s/0mscl/"//TRIM(MAVCHAR)//"/g' input")
      
     OPEN(11,FILE="initcond.ini",STATUS="OLD")
     WRITE(11,*) '"'//TRIM(FILEPOT)//'"' !FILEPOT
     WRITE(11,*) "1.0"          !TSX
     WRITE(11,*) SX(SIM)        !RSX
     WRITE(11,*) MCLUSTER       !CLUSTER MASS
     WRITE(11,*) "0."           !T0 FOR 2NDGEN
     WRITE(11,*) "-1.0"         !VIRIAL TIME (USELESS HERE)
     WRITE(11,*) "1.0"          !FINAL TIME (USELESS HERE)
     CLOSE(11)
  END IF

  IF(RUN.EQ.2.AND.GEN.EQ.1) THEN
     !CALL SCALING(REAL(MCLUSTER/NPART),NPART,SX(SIM),TSX,VSX)
     !print*,TSX,VSX,"caxa1"
     CALL SYSTEM("grep 'L SCALING' output.txt>tempscaling.dat")
     OPEN(11,FILE="tempscaling.dat",STATUS="OLD")
     READ(11,*) DUMMY(1:10),VSX,DUMMY(1:2),TSX
     CLOSE(11)
     CALL SYSTEM("rm tempscaling.dat")
     OPEN(14,FILE="scaling.dat",STATUS="REPLACE")
     WRITE(14,*) SX(SIM),MCLUSTER,VSX,TSX
     CLOSE(14)
     OPEN(11,FILE="initcond.ini",STATUS="REPLACE")
     WRITE(11,*) '"'//TRIM(FILEPOT)//'"' !FILEPOT
     WRITE(11,*) TSX            !TSX
     WRITE(11,*) SX(SIM)        !RSX
     WRITE(11,*) MCLUSTER       !CLUSTER MASS
     WRITE(11,*) "0."           !T0 FOR 2NDGEN
     WRITE(11,*) TVIR           !VIRIAL TIME 
     WRITE(11,*) TCOL           !FINAL TIME 
     CLOSE(11)
     FREQ=0.2/(25.*TSX)
     IF(CONT.EQ.3) THEN
31      DT=0.1
        FREQ=DT/(25.*TSX)
        NFRAMES=(TCOL/TSX)/(25*FREQ)
        WRITE(*,'(A,F5.2,A,I4,A)') "MORE RESOLUTION SIMULATION WITH DT =",DT," AND ",NFRAMES," FRAMES"
        PRINT*,"ENOUGH? YES=1, DIFFERENT NUMBER?=2"
        READ(*,*) CONT1
        IF(CONT1.LT.1.OR.CONT1.GT.2) GOTO 31
        IF(CONT1.EQ.2) THEN
           PRINT*,"WRITE NEW DT"
           READ(*,*) DT
           GOTO 31
        END IF
     END IF
     WRITE(FREQCHAR,17) FREQ
     CALL SYSTEM("sed -i '1s/4.0/4000000/g' input")
     CALL SYSTEM("sed -i '3s/0.05/"//TRIM(FREQCHAR)//"/g' input")
  END IF

  IF(GEN.EQ.2.AND.RUN.EQ.2) THEN
     OPEN(11,FILE="initcond.ini",STATUS="OLD")
     READ(11,*) DUMMY(1)
     READ(11,*) TSX            !TSX
     READ(11,*) SXPREV
     READ(11,*) DUMMY(1)
     READ(11,*) DUMMY(1)
     READ(11,*) TVIR1
     CLOSE(11)

     OPEN(11,FILE="initcond.ini",STATUS="REPLACE")
     WRITE(11,*) '"'//TRIM(FILEPOT)//'"' !FILEPOT
     WRITE(11,*) TSX            !TSX
     WRITE(11,*) SXPREV         !RSX
     WRITE(11,*) MCLUSTER       !CLUSTER MASS
     WRITE(11,*) TCOL           !T0 FOR 2NDGEN
     WRITE(11,*) "0.0"          !VIRIAL TIME=0 ALWAYS 2NDGEN
     WRITE(11,*) TEND-TCOL      !FINAL TIME 
     CLOSE(11)
     
     OPEN(11,FILE="input",STATUS="OLD")
     READ(11,*) DUMMY(1)
     READ(11,*) NPART1
     OPEN(11,FILE="inpoutput",STATUS="REPLACE")
     WRITE(11,*) (TCOL-TVIR1)/TSX-0.1,"0",NPART1," 1 ",NPART1,MCLUSTER," 1 "
     CLOSE(11)
     NPART0=NPART1
     CALL SYSTEM("ronb6++.x < inpoutput>tempro.dat")
     CALL SYSTEM("tail -n1 massposvel.txt >> tempro.dat")
     CALL SYSTEM("tail -n1 massposvellast.txt >> tempro.dat")
     OPEN(11,FILE="tempro.dat",STATUS="OLD")
     READ(11,*) DUMMY(1)
     READ(11,*) DUMMY(1)
     READ(11,*) SNORI,FRAMES
     READ(11,*) DUMMY(1:8),TALLF
     READ(11,*) DUMMY(1:8),TLASTF
     CLOSE(11)     
     CALL SYSTEM("rm tempro.dat")
     WRITE(*,'(A,I4,A,I5,A)') "I READ ",FRAMES," FRAMES, WITH ",SNORI," MASSIVE STARS"
     IF(ABS(TALLF-TLASTF).GT.0.1) PRINT*,"WARNING!!!, LAST FRAME NOT CORRECT"
     OPEN(11,FILE="info1stgen.dat",STATUS="REPLACE")
     WRITE(11,*) SNORI,FRAMES,"MASSIVAS AND FRAMES"
     WRITE(11,*) TALLF,TLASTF,"TIME LAST FRAME, REAL TIME USED AS LAST FRAME (NB)"
     CLOSE(11)
     OPEN(11,FILE="massposvellast.txt",STATUS="OLD")
     DO I=1,NPARTALL
        READ(11,*,END=112) MAT(1:8,I)
     END DO
112  CLOSE(11)
     NPART1=I-1
     CALL SYSTEM("rm masivas.txt  massposvel0.txt massposvel.txt")
     IF(NPART1.GE.NPARTALL-1) THEN
        PRINT*,"I AM PROBABLY SKIPPING PARTICLES FROM 1STGEN, YOU SHOULD INCREASE NPARTALL",&
             GEN,NPART1,NPARTALL
        STOP
     END IF
     
     CALL CREATETABLE(MAT(:,1:NPART1),NPART1,MCLUSTER,MATTAB,GEN,TCOL,TEND,MATSN1,SN1,NPARTALL,1)
          
     !FILECLUSTER="cluster_M"//TRIM(MASSCHAR)//".00_1.txt"
     IF(MC.EQ.4.OR.MC.EQ.5) FILECLUSTER=FILECLUSTER2
     
     OPEN(11,FILE=FILECLUSTER,STATUS="OLD")
     READ(11,*) DUMMY(1)
     DO I=1,NPARTALL
        READ(11,*,END=113) MAT2(1:7,I)
        MAT2(1,I)=MAT2(1,I)*MCLUSTER2/MCLUSTER
        IF(SECONDRH.EQ.1) MAT2(2:4,I)=MAT2(2:4,I)*SX2(SIM+5)/SX(SIM)!(1.30/1.68)
        IF(SECONDRH.EQ.2) MAT2(2:4,I)=MAT2(2:4,I)*SX2(SIM+5)/SX(SIM)!(2.60/1.68)
        MAT2(8,I)=I
     END DO
113  CLOSE(11)
     NPART2=I-1
     IF(NPART2.GE.NPARTALL-1) THEN
        PRINT*,"I AM PROBABLY SKIPPING PARTICLES FROM 2NDGEB, YOU SHOULD INCREASE NPARTALL",&
             GEN,NPART2,NPARTALL
        STOP
     END IF
     CALL CREATETABLE(MAT2(:,1:NPART2),NPART2,MCLUSTER,MATTAB,GEN,TCOL,TEND,MATSN2,SN2,NPARTALL,2)
     IF(SN1.GE.SN2) SN=SN1
     IF(SN2.GE.SN1) SN=SN2
     
     DO I=1,SN
        IF(I.LE.SN1) THEN
           MATSNALL(1:3,I)=MATSN1(1:3,I)
           MATSNALL(2,I)=MATSNALL(2,I)-TCOL
        END IF
        IF(I.LE.SN2) THEN
           MATSNALL(1:3,I+SN1)=MATSN2(1:3,I)
           MATSNALL(1,I+SN1)=MATSNALL(1,I+SN1)+NPART1
        END IF
     END DO
     CALL ORDER(MATSNALL,2,3,SN1+SN2,1) !ARRAY,COLTOORDER,NCOL,NLINES,1MENORMAYOR,2MAYORMENOR
     OPEN(13,FILE="TableSN.dat",STATUS="REPLACE")
     SHIFT=0.
     DO I=1,SN1+SN2
        IF(MATSNALL(2,I).LT.0) THEN
           IF(ABS(MATSNALL(2,I)).GT.0.1)THEN
              PRINT*,"NEGATIVE SN, ERROR"
              STOP
           ELSE
              MATSNALL(2,I)=I*1E-4
           END IF
           PRINT*,"SN EXPLOSION IN SMALL NEGATIVE TIME",I,MATSNALL(2,I),"Myr"
        END IF
        WRITE(13,*) INT(MATSNALL(1,I)),MATSNALL(2:3,I)
     END DO
     CLOSE(13)
     !CALL SCALEVEL2NDGEN(MAT2(:,1:NPART2),NPART2,MAT(:,1:NPART1),NPART1,&
     !     FILEPOT,TCOL,SX(SIM),MCLUSTER,CTEK)
     
     OPEN(13,FILE="scaling.dat",STATUS="OLD")
     READ(13,*) DUMMY(1:2),VSX
     CLOSE(13)
     
     CALL QVAL(MAT(:,1:NPART1),NPART1,MAT2(:,1:NPART2),NPART2,TCOL,MCLUSTER,SX(SIM),VSX,1,&
     FILEPOT,CTEK,VIRF,TSX,TEND)
     OPEN(12,FILE="dat.10",STATUS="REPLACE")
     DO I=1,NPART1
        WRITE(12,*) MAT(1:7,I)
     END DO
     DO I=1,NPART2
        !WRITE(12,*) MAT2(1:4,I),CTEK*MAT2(5:7,I)
        WRITE(12,*) MAT2(1,I),MAT2(2:4,I),CTEK*MAT2(5:7,I)
     END DO
     CLOSE(12)
     
     IF(NPART1+NPART2.LT.1000)  WRITE(NPCHAR,12) NPART1+NPART2
     IF(NPART1+NPART2.GE.1000.AND.NPART.LT.10000) WRITE(NPCHAR,13) NPART1+NPART2
     IF(NPART1+NPART2.GE.10000.AND.NPART.LT.100000) WRITE(NPCHAR,14) NPART1+NPART2
     IF(NPART1+NPART2.GE.100000.AND.NPART.LT.1000000) WRITE(NPCHAR,15) NPART1+NPART2

     IF(NPART0.LT.1000)  WRITE(NPCHAR0,12) NPART0
     IF(NPART0.GE.1000.AND.NPART.LT.10000) WRITE(NPCHAR0,13) NPART0
     IF(NPART0.GE.10000.AND.NPART.LT.100000) WRITE(NPCHAR0,14) NPART0
     IF(NPART0.GE.100000.AND.NPART.LT.1000000) WRITE(NPCHAR0,15) NPART0
     
     CALL SYSTEM("sed -i '2s/"//TRIM(NPCHAR0)//"/"//TRIM(NPCHAR)//"/g' input")
     CALL SYSTEM("sed -i '12s/10000./10001./g' input")
  END IF
10 FORMAT(I1)
11 FORMAT(I2)
12 FORMAT(I3)
13 FORMAT(I4)
14 FORMAT(I5)
15 FORMAT(I6)
16 FORMAT(F6.3)
17 FORMAT(F8.5)
 
END SUBROUTINE MODFILES

SUBROUTINE QVAL(MAT1,NP1,MAT2,NP2,TT,MCLUSTER,RSX,VSX,F,&
     FILEPOT,CTEK,VIRF,TSX,TEND)
  
  IMPLICIT NONE
  INTEGER NMAX4
  PARAMETER (NMAX4=5000)
  INTEGER NTOT2,F,NFILESPOT,IPOT2,NLINES,NP1,NP2,VIRF
  REAL MAT1(8,NP1),MAT2(8,NP2),RSX,VSX,MCLUSTER,TT,CTEK,TSX,TEND
  CHARACTER*300 FILEPOTINFOALL,FILEPOT
  CHARACTER*300 PATHPOTALL(NMAX4)

  
  INTEGER I,J,K !LOOP
  INTEGER IPOT,NMOD,NAMEGEN(NP1+NP2),CHANGETT  !AUX

  REAL M(NP1+NP2),XYZ(3,NP1+NP2),VXYZ(3,NP1+NP2),MAT(7,NP1+NP2),Q1,Q2,Q,MASSTIMEPOT(2,NMAX4),RFPOT(3,NMAX4)
  REAL G,DUMMY,MP,KIN1,KIN2,POTGASSTARS1,POTGASSTARS2,POTSTARS
  REAL RMIN,RMAX,RSTAR,POTHERE,MIMJRIJ(NP1+NP2),M1,M2,Q_i

  CHANGETT=0
  NFILESPOT=5000
  NTOT2=NP1+NP2
  DO I=1,NP1
     MAT(1:7,I)=MAT1(1:7,I)
     NAMEGEN(I)=1
  END DO
  DO I=1,NP2
     MAT(1:7,I+NP1)=MAT2(1:7,I)
     NAMEGEN(I+NP1)=2
  END DO
  
  IF(F.EQ.1) IPOT2=0
  !PRINT*,"READING AND SCALING POTENTIAL"
  G=4.302E-03
  M(1:NTOT2)=MAT(1,1:NTOT2)
  XYZ(1:3,1:NTOT2)=MAT(2:4,1:NTOT2)
  VXYZ(1:3,1:NTOT2)=MAT(5:7,1:NTOT2)
  
  FILEPOTINFOALL=TRIM(FILEPOT)//"file_time_Mcloud_file.dat"
21 OPEN(21,FILE=FILEPOTINFOALL,STATUS="OLD")
  DO I=1,1000
     READ(21,*) MASSTIMEPOT(2,I),MASSTIMEPOT(1,I),PATHPOTALL(I)
     IPOT=I
     IF(MASSTIMEPOT(2,I).GE.TT) EXIT
  END DO
  CLOSE(21)
  !IF(IPOT.GT.1) IPOT=IPOT-1
  IF(IPOT.EQ.IPOT2) GOTO 1112

  IF(I.GE.NFILESPOT) IPOT=NFILESPOT
  IF(VIRF.EQ.2) IPOT=IPOT-1
  IPOT2=IPOT
  !FILEPOTH=TRIM(PATHPOTALL(IPOT))
  
  OPEN(1111,FILE=TRIM(FILEPOT)//TRIM(PATHPOTALL(IPOT)),STATUS="OLD")                                    
  !print*,trim(pathPOTALL(IPOT))
  DO I=1,NMAX4
     READ(1111,*,END=1111) RFPOT(3,I),RFPOT(1,I),RFPOT(2,I) !UNITS IN ASTRO
     IF(RFPOT(1,I).GT.100.AND.VIRF.NE.2) THEN !CHECK CORRECT SNAPSHOT AFTER COLLAPSE
        TT=TT+0.01
        CHANGETT=1
        GOTO 21
     END IF
     RFPOT(3,I)=RFPOT(3,I)/RSX
     RFPOT(1,I)=RFPOT(1,I)*RSX**2/(G*MCLUSTER)
  END DO
1111 CLOSE(1111)
  NLINES=I-1
  IF(CHANGETT.NE.0) THEN
     OPEN(11,FILE="initcond.ini",STATUS="REPLACE")
     WRITE(11,*) '"'//TRIM(FILEPOT)//'"' !FILEPOT
     WRITE(11,*) TSX            !TSX
     WRITE(11,*) RSX            !RSX
     WRITE(11,*) MCLUSTER       !CLUSTER MASS
     WRITE(11,*) TT             !T0 FOR 2NDGEN
     WRITE(11,*) "0.0"          !VIRIAL TIME=0 ALWAYS 2NDGEN
     WRITE(11,*) TEND-TT        !FINAL TIME 
     CLOSE(11)
  END IF
  PRINT*,"WORKING WITH FILE ",TRIM(PATHPOTALL(IPOT))!,RFPOT(3,1)*RSX,RFPOT(3,NLINES)*RSX
1112 MP=MASSTIMEPOT(1,IPOT) !FRACTION OF MASSCLOUD/MCLUSTER
  RMIN=RFPOT(3,1)     !MIN RAD FROM CLOUD POTENTIAL
  RMAX=RFPOT(3,NLINES)!MAX RAD FROM CLOUD POTENTIAL
  POTGASSTARS1=0   !POTENCIAL THAT STARS FEEL FROM GAS
  POTGASSTARS2=0   !POTENCIAL THAT STARS FEEL FROM GAS
  POTSTARS=0       !POTENTIAL BETWEEN STARS
  KIN1=0
  KIN2=0
  !PRINT*,"CALCULATING ENERGIES"!,rsx,g,mcluster,mp
  NMOD=1000
  IF(NTOT2.GT.2000.AND.NTOT2.LT.3000) NMOD=2000
  IF(NTOT2.GT.3000.AND.NTOT2.LT.4000) NMOD=3000
  IF(NTOT2.GT.4000.AND.NTOT2.LT.5000) NMOD=4000
  IF(NTOT2.GT.5000.AND.NTOT2.LT.6000) NMOD=5000
  IF(NTOT2.GT.6000.AND.NTOT2.LT.7000) NMOD=6000
  IF(NTOT2.GT.7000.AND.NTOT2.LT.8000) NMOD=7000
  IF(NTOT2.GT.8000.AND.NTOT2.LT.9000) NMOD=8000
  IF(NTOT2.GT.9000.AND.NTOT2.LT.10000) NMOD=9000
  IF(NTOT2.GT.10000.AND.NTOT2.LT.20000) NMOD=10000
  IF(NTOT2.GT.20000.AND.NTOT2.LT.30000) NMOD=20000
  IF(NTOT2.GT.30000.AND.NTOT2.LT.40000) NMOD=30000
  IF(NTOT2.GT.40000.AND.NTOT2.LT.50000) NMOD=40000
  IF(NTOT2.GT.50000) NMOD=50000
  IF(NTOT2.GT.100000) NMOD=100000
  IF(NTOT2.GT.200000) NMOD=200000
  IF(NTOT2.GT.400000) NMOD=400000
  DO I=1,NTOT2
     IF(MOD(I,NMOD).EQ.0) WRITE(*,'(A, I6, A, I6,A, F5.2,A,I5, A)') &
          "CALCULATING ENERGY FOR ",I,", OF ",NTOT2,", AT ",TT," MYR"! AT FRAME ",F
     !IF(NAMEGEN(I).LE.1) KIN1=KIN1+0.5*M(I)*(VXYZ(1,I)**2+VXYZ(2,I)**2+VXYZ(3,I)**2) !KINETIC1 ENERGY SUM !!!MODONLY2NDGEN
     IF(NAMEGEN(I).EQ.2) KIN2=KIN2+0.5*M(I)*(VXYZ(1,I)**2+VXYZ(2,I)**2+VXYZ(3,I)**2) !KINETIC2 ENERGY SUM
     IF(NAMEGEN(I).EQ.2) RSTAR=(XYZ(1,I)**2+XYZ(2,I)**2+XYZ(3,I)**2)**0.5      !RAD TO THE CENTER !!!MODONLY2NDGEN
     IF(RSTAR.GE.RMIN.AND.RSTAR.LT.RMAX.AND.NAMEGEN(I).EQ.2) THEN   !IF RAD INSIDE GAS ARRAY !!!MODONLY2NDGEN
        DO J=1,NLINES                           !SEARCH FOR GAS POTENTIAL AT STAR RADII
           IF(RFPOT(3,J).GE.RSTAR) THEN            !RAD IN GAS POTENTIAL
              POTHERE=0
              DO K=1,3
                 POTHERE=POTHERE+(RFPOT(1,J)/RSTAR)*(XYZ(K,I))**2
              END DO
              EXIT                              !DONE
           END IF
        END DO
     ELSE
        POTHERE=0
     END IF
     IF(RSTAR.GE.RMIN.AND.RSTAR.LT.RMAX) THEN
        !IF(NAMEGEN(I).LE.1) POTGASSTARS1=POTGASSTARS1+M(I)*POTHERE !GAS POTENTIAL AT STAR RADII SUM !!!MODONLY2NDGEN
        IF(NAMEGEN(I).EQ.2) POTGASSTARS2=POTGASSTARS2+M(I)*POTHERE !GAS POTENTIAL AT STAR RADII SUM
     END IF
     !POTGASSTARS1=POTGASSTARS1
     !POTGASSTARS2=POTGASSTARS2
!$OMP PARALLEL DO PRIVATE(J)     
     DO J=I+1,NTOT2
        MIMJRIJ(J)=M(I)*M(J)/((XYZ(1,I)-XYZ(1,J))**2+(XYZ(2,I)-XYZ(2,J))**2+(XYZ(3,I)-XYZ(3,J))**2)**0.5 !POTENTIAL BETWEEN STARS
     END DO
!$OMP END PARALLEL DO     
     POTSTARS=POTSTARS+SUM(MIMJRIJ(I+1:NTOT2))
  END DO
  !POTSTARS=POTSTARS
  !Q1=KIN1/(POTGASSTARS1+POTSTARS)
  !Q2=KIN2/(POTGASSTARS2+POTSTARS)
  !Q=(KIN1+KIN2)/(POTGASSTARS1+POTGASSTARS2+POTSTARS)
  Q_i = 0.5
  IF(VIRF.EQ.3) Q_i=0.4
  IF(VIRF.EQ.4) Q_i=0.2
  IF(VIRF.EQ.5) Q_i=0.3
  IF(VIRF.EQ.6) Q_i=0.35
  CTEK=(Q_i*(POTGASSTARS2+POTSTARS)/KIN2)**0.5
  Q2=CTEK**2*KIN2/(POTGASSTARS2+POTSTARS)
  !print*,q1,q2,q,KIN1,KIN2,POTGASSTARS1,POTGASSTARS2,POTSTARS,CTEK
  !print*,ctek**2*kin2/(POTGASSTARS2+POTSTARS)
  WRITE(*,'(A,F5.2,A,F5.2)') "SCALING 2NDGEN WITH A CONSTANT OF",CTEK," VIRIAL RATIO OF 2NDGEN, Q =",Q2
END SUBROUTINE QVAL


SUBROUTINE NOTUSED_SCALEVEL2NDGEN(MAT,NPART,MAT1,NPART1,FILEPOT,TCOL,SX,MCLUSTER,CTEK)
  IMPLICIT NONE
  INTEGER NPART,NPART1
  REAL MAT(8,NPART),MAT1(8,NPART1),TCOL,SX,MCLUSTER,CTEK
  CHARACTER*300 FILEPOT

  INTEGER I,J,K
  REAL T,G,MATPOT(3,5000)
  CHARACTER*300 FILEPOTINFOALL,FILEPOTINFO(1000),DUMMY
  INTEGER NLPOT,IPOT
  REAL*8 KIN,POTGAS,POTHERE,POTSTARS,R,RIJ,CTE
  G=4.30E-03
  FILEPOTINFOALL=TRIM(FILEPOT)//"file_time_Mcloud_file.dat"
  OPEN(21,FILE=FILEPOTINFOALL,STATUS="OLD")
  DO I=1,1000
     READ(21,*) T,DUMMY,FILEPOTINFO(I)
     IF(T.GT.TCOL) EXIT
  END DO
  CLOSE(21)
  IPOT=I-1
  PRINT*,"SCALING 2NDGEN WITH ",TRIM(FILEPOTINFO(IPOT))
  FILEPOTINFO(IPOT)=TRIM(FILEPOT)//TRIM(FILEPOTINFO(IPOT))
  OPEN(21,FILE=FILEPOTINFO(IPOT),STATUS="OLD")
  DO I=1,5000
     READ(21,*,END=21) MATPOT(1:3,I) !R,F,POT
     MATPOT(1,I)=MATPOT(1,I)/SX
     MATPOT(2,I)=MATPOT(2,I)*SX**2/(G*MCLUSTER)
  END DO
21 CLOSE(21)
  NLPOT=I-1
  KIN=0
  POTGAS=0
  POTSTARS=0

  DO I=1,NPART
     KIN=KIN+0.5*MAT(1,I)*(MAT(5,I)**2+MAT(6,I)**2+MAT(7,I)**2)
     R=(MAT(2,I)**2+MAT(3,I)**2+MAT(4,I)**2)**0.5
     DO J=1,NLPOT
        IF(R.GT.MATPOT(1,NLPOT)) EXIT
        IF(R.LT.MATPOT(1,1)) EXIT
        IF(MATPOT(1,J).GE.R) THEN
           POTHERE=0
           DO K=2,4
              POTHERE=POTHERE+(MATPOT(2,J)/MATPOT(1,J))*(MAT(K,I)**2)
           END DO
           POTGAS=POTGAS+MAT(1,I)*POTHERE
           EXIT
        END IF
     END DO
     DO J=1,NPART
        IF(J.GT.I) THEN
           RIJ=((MAT(2,I)-MAT(2,J))**2+(MAT(3,I)-MAT(3,J))**2+(MAT(4,I)-MAT(4,J))**2)**0.5
           POTSTARS=POTSTARS+MAT(1,I)*MAT(1,J)/RIJ
        END IF
     END DO
     DO J=1,NPART1
        RIJ=((MAT(2,I)-MAT1(2,J))**2+(MAT(3,I)-MAT1(3,J))**2+(MAT(4,I)-MAT1(4,J))**2)**0.5
        POTSTARS=POTSTARS+MAT(1,I)*MAT1(1,J)/RIJ
     END DO
  END DO
  potgas=0!potgas*100
  CTE=(0.5*(POTGAS+POTSTARS)/KIN)**0.5
  CTEK=CTE
  print*,kin/(potSTars+potgas),kin,potstars,potgas,CTE,CTEK
  print*,CTEK**2*kin/(potSTars+potgas)
  stop
  
END SUBROUTINE NOTUSED_SCALEVEL2NDGEN


SUBROUTINE CREATETABLE(MAT,NPART,MCLUSTER,MATTAB,GEN,TCOL,TEND,MATSN,SN,NPARTALL,OPT)
  IMPLICIT NONE
  INTEGER NPART,GEN,SN,NPARTALL,OPT
  REAL MAT(8,NPART),MCLUSTER,MATTAB(2,5000),TCOL,TEND,MATSN(3,NPARTALL)

  INTEGER I,J !LOOPS
  REAL MATM(2,NPART),T0,TEND2,MMAX,M
  INTEGER J1
  
  IF(OPT.EQ.1) T0=0.
  IF(OPT.EQ.2) T0=-TCOL
  TEND2=TEND+T0+0.5
  DO I=1,5000
     IF(MATTAB(1,I).GT.TEND2) THEN
        MMAX=MATTAB(2,I)
        EXIT
     END IF
  END DO
  SN=0
  DO I=1,NPART
     IF(MAT(1,I)*MCLUSTER.GT.MMAX) THEN
        SN=SN+1
        MATM(1,SN)=MAT(1,I)*MCLUSTER
        MATM(2,SN)=I
     END IF
  END DO
  
  CALL ORDER(MATM,1,2,SN,2) !ARRAY,COLTOORDER,NCOL,NLINES,1MENORMAYOR,2MAYORMENOR
  
  J1=1
  DO I=1,SN
     IF(MATM(1,I).GT.MATTAB(2,2)) THEN
        IF(MATM(1,I).GT.MATTAB(2,1)+1) THEN
           PRINT*,"MASS TOO BIG!!!!",MATM(1,I),MCLUSTER
           STOP
        END IF
        WRITE(*,'(A,F7.2,A,F5.2,A)') &
             "BIG MASS USING MIN TIME FOR SN",MATM(1,I)," Mo,",&
             MATTAB(1,1)," Myr"
        MATSN(1,I)=MATM(2,I)          !LABEL
        MATSN(3,I)=MATM(1,I)          !MASS
        MATSN(2,I)=MATTAB(1,1)        !TIME
        GOTO 10
     END IF
     DO J=J1,5000
        IF(J.EQ.5000) THEN
           PRINT*,"MASS NOT FOUND IN TABLE",MATM(1,I)
           STOP
        END IF
        IF(MATTAB(2,J).LT.MATM(1,I)) THEN           
           MATSN(1,I)=MATM(2,I)          !LABEL
           MATSN(3,I)=MATM(1,I)          !MASS
           M=(MATTAB(1,J)-MATTAB(1,J-1))/(MATTAB(2,J)-MATTAB(2,J-1)) !SLOPE DT/DM
           MATSN(2,I)=(MATSN(3,I)-MATTAB(2,J-1))*M+MATTAB(1,J-1)
           J1=J-1
           EXIT
        END IF
     END DO
10 END DO
  
  IF(GEN.EQ.1) THEN
     OPEN(13,FILE="TableSN.dat",STATUS="REPLACE")
     DO I=1,SN
        WRITE(13,*) INT(MATSN(1,I)),MATSN(2:3,I)
     END DO
     CLOSE(13)
  END IF

END SUBROUTINE CREATETABLE

SUBROUTINE INITIOPTION(R136,MC,POT,RHO,SFE,SEG,SIMF,OPT,WORKFOLDER,SIMICHAR,GEN,COL,TCOL,TVIR,MCLUSTER,&
     NPARTALL,SX,FILEPOT,MATTAB,TEND,CONT1,VIRF,SECONDSEG,WORKFOLDER2,SFES,SFESCHAR,MCLUSTER2,SECONDRH,&
     HOME2,SFERH,CLUSTERORI,SECONDSEGHIGH,FIMF)
  IMPLICIT NONE
  INTEGER R136,MC,POT,RHO,SFE,SEG,SIMF,GEN,COL,NPARTALL,CONT1,VIRF,SECONDSEG,SFES(2),SECONDRH,SECONDSEGHIGH,FIMF
  REAL TCOL,TVIR,MCLUSTER,SX(10),MATTAB(2,5000),TEND,MCLUSTER2
  CHARACTER*20 RHOICHAR2,SFEICHAR2,SFEICHAR3
  CHARACTER*300 WORKFOLDER,WORKFOLDER2(4),FILEPOT,SIMICHAR(3,10),SFESCHAR(3),HOME2
  CHARACTER*20 OPT(6),CLUSTERORI(10) !SPLITPATH
  CHARACTER*30 SFERH
  
  Logical :: file_exists(10)
  INTEGER RHOI,SFEI,OPTCONT,SIMMRI,CONT
  CHARACTER*20 RHOICHAR,SFEICHAR,SIMTEMP,SIMMR,DUMMY(2)
  CHARACTER*50 FILEPOT2,HOME!,FILETEMP
  CHARACTER*300 FILETCOL,SIMICHAREXTRA(19,10),INSTRING
  INTEGER I,INDEX
  REAL MCTEMP
  HOME="/export/home/rdomingu/"
  HOME2="/export/scratch/rdomingu/"
  CALL SPLITPATH(OPT,WORKFOLDER,WORKFOLDER2)
  VIRF=0
  SECONDSEG=1
  SECONDRH=0
  IF(TRIM(OPT(1)).EQ."R136") THEN
     R136=1
  ELSE
     R136=0
  END IF
  SIMF=10
  IF(R136.EQ.1) SIMF=5
  DO I=1,10
     IF(I.LT.10) WRITE(SIMTEMP,10) I
     IF(I.GE.10.AND.I.LT.100)  WRITE(SIMTEMP,11) I
     SIMICHAR(1,I)="/sim_"//TRIM(SIMTEMP)//"/1stgen"   !1ST CLUSTER
     SIMICHAR(2,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-2" !VIR AFTER COL
     SIMICHAR(3,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen"   !DATA FOR 2ND CLUSTER
     SIMICHAREXTRA(1,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-3" !VIR BEFORE COL
     SIMICHAREXTRA(2,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-4" !VIR AFTER COL AND 2ND CLUSTER SEG
     SIMICHAREXTRA(3,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-5" !RH1.0PC
     SIMICHAREXTRA(4,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-6" !RH1.0PC
     SIMICHAREXTRA(5,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-7" !FULL-IMF
     SIMICHAREXTRA(6,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-8" !paper-IMF
     SIMICHAREXTRA(7,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-9" !
     SIMICHAREXTRA(8,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-10" !
     SIMICHAREXTRA(9,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-11" !
     SIMICHAREXTRA(10,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-12" !
     SIMICHAREXTRA(11,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-13" !
     SIMICHAREXTRA(12,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-14" !
     SIMICHAREXTRA(13,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-15" !RH1.0PC-MMAX300Mo
     SIMICHAREXTRA(14,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-16" !RH1.0PC-NIMF-QI0.4
     SIMICHAREXTRA(15,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-17" !RH1.0PC-MMAX300Mo-QI0.4
     SIMICHAREXTRA(16,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-18" !RH1.0PC-NIMF-QI0.2
     SIMICHAREXTRA(17,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-19" !RH1.0PC-MMAX300Mo-QI0.2
     SIMICHAREXTRA(18,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-20" !RH1.0PC-NIMF-QI0.3
     SIMICHAREXTRA(19,I)="/sim_"//TRIM(SIMTEMP)//"/2ndgen-21" !RH1.0PC-NIMF-QI0.35
     CLUSTERORI(I)="/c"//TRIM(SIMTEMP)
  END DO
  
  POT=0
  IF(TRIM(OPT(2)).EQ."rhoUniform") POT=1 !WARPFIELD 
  !IF(TRIM(OPT(2)).EQ.) POT=2 !PLUMMER AP=1.0
  !IF(TRIM(OPT(2)).EQ.) POT=3 !PLUMMER AP!=1.0
  !IF(TRIM(OPT(2)).EQ.) POT=4 !NO GAS
  IF(POT.EQ.0.OR.POT.GT.1) THEN
     IF(POT.EQ.0) PRINT*,"POTENTIAL NOT RECOGNIZED, STOPPING",TRIM(OPT(2))
     IF(POT.GT.1) PRINT*,"NOT IMPLEMENTED, STOPPING",TRIM(OPT(2))
     STOP
  END IF
  DO RHOI=1,10
     IF(RHOI.LT.10) WRITE(RHOICHAR,13) 1000*RHOI
     IF(RHOI.GE.10.AND.RHOI.LT.100) WRITE(RHOICHAR,14) 1000*RHOI
     RHOICHAR2=TRIM(RHOICHAR)
     RHOICHAR="rho"//TRIM(RHOICHAR)
     IF(TRIM(RHOICHAR).EQ.TRIM(OPT(3))) EXIT
  END DO
  RHO=RHOI
  IF(RHO.GT.10) THEN
     PRINT*,"RHO NOT RECOGNIZED, STOPPING",TRIM(OPT(3))
     STOP
  END IF
  
  
  SEG=0
  IF(TRIM(OPT(5)).EQ."SEG") SEG=1
  IF(TRIM(OPT(5)).EQ."NOSEG") SEG=2
  IF(SEG.EQ.0) THEN
     PRINT*,"SEGREGATION NOT RECOGNIZED, STOPPING ",TRIM(OPT(5))
     STOP
  END IF

  MC=0
  IF(TRIM(OPT(6)).EQ."M5") THEN
     MC=1
     MCLUSTER=10**5!*(SFE/100.)
     NPARTALL=10000
  END IF
  IF(TRIM(OPT(6)).EQ."M6") THEN
     MC=2
     MCLUSTER=10**6!*(SFE/100.)
     NPARTALL=80000
  END IF
  IF(TRIM(OPT(6)).EQ."M7") THEN
     MC=3
     MCLUSTER=10**7!*(SFE/100.)
     NPARTALL=200000
  END IF
  IF(TRIM(OPT(6)).EQ."M5.5") THEN
     MC=4
     MCLUSTER=10**5.5!*(SFE/100.)
     NPARTALL=110000
  END IF
  IF(TRIM(OPT(6)).EQ."M6.5") THEN
     MC=5
     MCLUSTER=10**6.5!*(SFE/100.)
     NPARTALL=200000
  END IF
  
  IF(MC.EQ.0.OR.MC.EQ.1.OR.MC.EQ.3) THEN
     IF(MC.EQ.0)PRINT*,"CLOUD MASS NOT RECOGNIZED, STOPPING ",TRIM(OPT(6))
     IF(MC.NE.0)PRINT*,"CLOUD MASS NOT IMPLEMENTED, STOPPING ",TRIM(OPT(6))
     STOP
  END IF

  IF(MC.EQ.4.OR.MC.EQ.5) THEN
     SFESCHAR(3)=TRIM(OPT(4))
     instring=TRIM(OPT(4))
     INDEX = SCAN(instring,"-")
     SFESCHAR(1) = instring(1:index-1)
     SFESCHAR(2) = instring(index+1:)
  END IF
  DO I=1,2
     IF(MC.EQ.4.OR.MC.EQ.5) OPT(4)=SFESCHAR(I)
     DO SFEI=1,20
        IF(SFEI.LT.10) THEN
           WRITE(SFEICHAR,10) SFEI
           SFEICHAR2=TRIM(SFEICHAR)
           SFEICHAR="SFE0.0"//TRIM(SFEICHAR)
        END IF
        IF(SFEI.GE.10.AND.SFEI.LT.100) THEN
           WRITE(SFEICHAR,11) SFEI
           SFEICHAR2=TRIM(SFEICHAR)
           SFEICHAR="SFE0."//TRIM(SFEICHAR)
        END IF
        IF(TRIM(SFEICHAR).EQ.TRIM(OPT(4))) EXIT
     END DO
     SFE=SFEI
     IF(MC.EQ.4.OR.MC.EQ.5) SFES(I)=SFEI
     IF((MC.EQ.4.OR.MC.EQ.5).AND.I.EQ.1) SFEICHAR3=SFEICHAR2
     IF(SFE.GT.20) THEN
        PRINT*,"SFE NOT RECOGNIZED, STOPPING ",TRIM(OPT(4))
        STOP
     END IF
     IF(MC.LT.4) EXIT
  END DO
  IF(MC.EQ.4.OR.MC.EQ.5) THEN
     SFEICHAR2=SFEICHAR3
     MCTEMP=MCLUSTER
     MCLUSTER=MCTEMP*(SFES(1)/100.)
     MCLUSTER2=MCTEMP*(SFES(2)/100.)
     ELSE
        MCLUSTER=MCLUSTER*(SFE/100.)
     END IF
  PRINT*,"I GOT THE NEXT AUTOMATIC OPTIONS"
  IF(MC.EQ.4.OR.MC.EQ.5) THEN
     WRITE(*,'(A4,I2,A,A12,I2,A,A9,I3,A,A15,I3,I3,A,A5,I2,A,A4,I2)') &
          TRIM(OPT(1)),R136,",",TRIM(OPT(2)),POT,",",TRIM(OPT(3)),RHO,", ", &
          TRIM(SFESCHAR(3)),SFES(1),SFES(2),",",TRIM(OPT(5)),SEG,", ",TRIM(OPT(6)),MC
  ELSE
     WRITE(*,'(A4,I2,A,A12,I2,A,A9,I3,A,A8,I3,A,A5,I2,A,A3,I2)') &
          TRIM(OPT(1)),R136,",",TRIM(OPT(2)),POT,",",TRIM(OPT(3)),RHO,",", &
          TRIM(OPT(4)),SFE,",",TRIM(OPT(5)),SEG,",",TRIM(OPT(6)),MC
  END IF
  
  PRINT*,"SHOULD I CONTINUE? YES=1, NO=0, SIM WITH MORE RESOLUTION=3, MOD=4"
  READ(*,*) CONT
  IF(CONT.EQ.0) STOP
  CONT1=CONT
  
  COL=-1
  TCOL=-1
  IF(R136.EQ.1) THEN
     COL=1
     TEND=8
  END IF
  IF(COL.NE.1) THEN
     PRINT*,"IS THERE A COLLAPSE? YES=1, NO=0"
     READ(*,*) COL
  END IF
  IF(COL.EQ.1) THEN
     PRINT*,"FIRST OR SECOND RUN? FIRST=1, SECOND=2"
     READ(*,*) GEN
     FILEPOT="/export/scratch/rdomingu/sim_WF_paper/sim_R136/WF_potential/testUni_cloudy_"
     IF(MC.EQ.4.OR.MC.EQ.5) THEN
        IF(MC.EQ.4) FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//"_rho_"//TRIM(RHOICHAR2)//"_SFE2_20_cloudy/Z1.00/"
        IF(MC.EQ.5) FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//"_rho_"//TRIM(RHOICHAR2)//"_cloudy/Z1.00/"
        FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//"0/"
     ELSE
        FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//"_rho_"//TRIM(RHOICHAR2)//"_cloudy2/Z1.00/"
        FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//".00/"
     END IF
     CALL SYSTEM("ls "//TRIM(FILEPOT)//">temppot.dat")
     OPEN(11,FILE="temppot.dat",STATUS="OLD")
     READ(11,*) FILEPOT2
     CLOSE(11)
     CALL SYSTEM("rm temppot.dat")
     IF(GEN.EQ.1) THEN    
        FILETCOL=TRIM(FILEPOT)//TRIM(FILEPOT2)//"/SFE"//TRIM(SFEICHAR2)//".00/cloudy/WARP_red_3.py"
        CALL SYSTEM('grep "t_col1" '//TRIM(FILETCOL)//' | head -n1  > tcol.txt')
     END IF
     OPEN(11,FILE="tcol.txt",STATUS="OLD")
     READ(11,*) DUMMY(1:2),TCOL
     CLOSE(11)
     IF(GEN.EQ.1.AND.CONT.NE.3) CALL COPYCLUSTERS(OPT,WORKFOLDER,SIMF,SIMICHAR,HOME,SFE,SEG,MC,MCLUSTER,&
          SFESCHAR,SFES,MCLUSTER2,HOME2)
  END IF
  IF(GEN.EQ.2) NPARTALL=GEN*NPARTALL
  IF(COL.LT.0.OR.TCOL.LT.0) THEN
     IF(COL.LT.0) PRINT*,"COLLAPSE?, STOPING"
     IF(TCOL.LT.0) PRINT*,"WHEN IS THE COLLPASE?, STOPING"
     STOP
  END IF
  PRINT*,"INPUT OPTIONS"
  IF(COL.EQ.0) THEN
     PRINT*,"NOT IMPLEMENTED"
     STOP
     PRINT*,"THERE IS NOT COLLAPSE"
     TCOL=14.5
  END IF

  OPEN(11,FILE="SX.dat",STATUS="OLD")
  DO I=1,10
     READ(11,*) SX(I)
  END DO
  CLOSE(11)


  TVIR=0.!-1. !! TIME FOR EVOLVE ONLY STARS NOT WARPFIELD
  IF(GEN.EQ.2) TVIR=0 !ALWAYS 0!!!
  IF(COL.EQ.1) THEN
     IF(CONT.EQ.3) THEN
        SIMF=1
        SIMICHAR(1,1)="/sim_moresolution/1stgen"
        SIMICHAR(2,1)="/sim_moresolution/2ndgen-2"
     END IF
     IF(CONT.EQ.3.AND.GEN.EQ.1) THEN
21      PRINT*,"WHICH SIM?"
        READ(*,*) SIMMR
        INQUIRE(FILE='sim_'//TRIM(SIMMR), EXIST=file_exists(1))
        IF(file_exists(1).EQV. .FALSE.) THEN
           PRINT*,"FOLDER NOT EXISTING, TRY AGAIN?=1, OR EXIT=0"
           READ(*,*) OPTCONT
           IF(OPTCONT.EQ.0) STOP
           GOTO 21
        END IF
        INQUIRE(FILE="sim_moresolution", EXIST=file_exists(2))
        IF(file_exists(2).EQV. .TRUE.) THEN
22         PRINT*,"FOLDER EXISTING, SHOULD I DELETE IT?=1, NO=0"
           READ(*,*) OPTCONT
           IF(OPTCONT.LT.0.OR.OPTCONT.GT.1) GOTO 22
           IF(OPTCONT.EQ.0) STOP
           IF(OPTCONT.EQ.1) CALL SYSTEM("rm -r sim_moresolution")
        END IF
        CALL SYSTEM('cp -r sim_'//TRIM(SIMMR)//' sim_moresolution')
        READ(SIMMR,'(I3)') SIMMRI
        SX(1)=SX(SIMMRI)
     END IF !IF MORERESOLUTION
     !FILEPOT="/export/scratch/rdomingu/sim_WF_paper/sim_R136/WF_potential/testUni_cloudy_"
     !FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//"_rho_"//TRIM(RHOICHAR2)//"_cloudy2/Z1.00/"
     !FILEPOT=TRIM(FILEPOT)//TRIM(OPT(6))//".00/"
     !CALL SYSTEM("ls "//TRIM(FILEPOT)//">temppot.dat")
     !OPEN(11,FILE="temppot.dat",STATUS="OLD")
     !READ(11,*) FILEPOT2
     !CLOSE(11)
     !CALL SYSTEM("rm temppot.dat")
     FILEPOT=TRIM(FILEPOT)//TRIM(FILEPOT2)//"/SFE"//TRIM(SFEICHAR2)//".00/cloudy/potential/"
    
     IF(GEN.EQ.1) WRITE(*,'(A,F5.2,A,F8.1,A)')"THERE IS A COLLAPSE AT",TCOL,&
             " Myr AND CLUSTER MASS ",MCLUSTER," Mo"
     IF(GEN.EQ.2) WRITE(*,'(A,F5.2,A,F8.1,A)')"THERE WAS A COLLAPSE AT",TCOL,&
          " Myr AND CLUSTER MASS ",MCLUSTER," Mo"
     PRINT*,"WORKING WITH ",TRIM(FILEPOT)
     IF(GEN.EQ.1) WRITE(*,'(A,F5.2,A)') "STOPPING AT COL TIME",TCOL," Myr"
     IF(GEN.EQ.2) WRITE(*,'(A,F5.2,A)') "FINAL TIME",TEND," Myr"
     IF(GEN.EQ.1) WRITE(*,'(A,F5.2,A)') "VIRIAL TIME",TVIR," Myr"
     IF(CONT.EQ.3) PRINT*,"SIMULATION WITH MORE RESOLUTION"
  END IF
  IF(GEN.EQ.2) THEN
     CALL SECONDGENOPTS(SEG,VIRF,SECONDSEG,SECONDRH,SECONDSEGHIGH,FIMF,SIMICHAR,SIMICHAREXTRA,SFERH)
  END IF
  PRINT*,"I WILL WORK IN ",TRIM(SIMICHAR(GEN,1))
  PRINT*,"SHOULD I CONTINUE? YES=1, NO=0"
  READ(*,*) CONT
  IF(CONT.EQ.0) STOP

  OPEN(11,FILE=TRIM(HOME)//"PhD_projects/programs/Table_masses.dat",STATUS="OLD")
  DO I=1,5000
     READ(11,*) MATTAB(1:2,I)
  END DO
  CLOSE(11)
     
  
10 FORMAT(I1)
11 FORMAT(I2)
12 FORMAT(I3)
13 FORMAT(I4)
14 FORMAT(I5)
END SUBROUTINE INITIOPTION

SUBROUTINE SPLITPATH(OPT,CWD,CWD2)
  IMPLICIT NONE
  CHARACTER*20 OPT(6)
  CHARACTER*300 CWD,CWD2(4)
  CHARACTER*300 INSTRING,STRING(13)
  INTEGER INDEX,I,J

  CALL GETCWD(CWD)
  PRINT*,"WORKING FOLDER",TRIM(CWD)

  INSTRING = TRIM(CWD)

  DO I=1,10 !RECOGNICE WHEN sim_WF_paper start
     INDEX = SCAN(instring,"/")
     STRING(I) = instring(1:index-1)
     STRING(I+1) = instring(index+1:)
     INSTRING = TRIM(STRING(I+1))
     IF(TRIM(STRING(I)).EQ."sim_WF_paper") EXIT
  END DO

  DO I=1,10
     INDEX = SCAN(instring,"/")
     STRING(I) = instring(1:index-1)
     STRING(I+1) = instring(index+1:)
     INSTRING = TRIM(STRING(I+1))
     J=I+1
     IF(TRIM(STRING(I+1)).EQ."SEG".OR.TRIM(STRING(I+1)).EQ."NOSEG") EXIT
  END DO
  DO I=1,3
     INSTRING = TRIM(STRING(2))
     INDEX = SCAN(instring,"_")
     IF(I.EQ.2) STRING(J+1) = instring(1:index-1)
     IF(I.LE.2) STRING(2) = instring(index+1:)
     IF(I.EQ.3) STRING(2) = instring(1:index-1)
  END DO
  
  INSTRING = TRIM(STRING(1))
  INDEX = SCAN(instring,"_")
  STRING(1) = instring(index+1:)
  
  DO I=1,J+1
     OPT(I)=STRING(I)
  END DO

  CWD2=""
  INSTRING = TRIM(CWD)
  DO I=1,10
     INDEX = SCAN(instring,"/")
     STRING(I) = instring(1:index-1)
     STRING(I+1) = instring(index+1:)
     INSTRING = TRIM(STRING(I+1))
     J=I+1
     IF(I.EQ.1) CWD2(1)=TRIM(CWD2(1))//TRIM(STRING(I))
     IF(I.GT.1) CWD2(1)=TRIM(CWD2(1))//"/"//TRIM(STRING(I))
     IF(TRIM(STRING(I+1)).EQ."NOSEG") EXIT
  END DO
  !CWD2(2)=TRIM(CWD2(1))
  CWD2(1)=TRIM(CWD2(1))//"SEG"
  CWD2(3)="SEG"
  CWD2(4)="NOSEG"
  
  
END SUBROUTINE SPLITPATH


SUBROUTINE ORDER(MAT0,OBJC,NCOL,LCOL,OPT)
  use omp_lib
  IMPLICIT NONE
  INTEGER OBJC,NCOL,LCOL,OPT
  REAL MAT0(NCOL,LCOL)

  INTEGER I,POSMIN,POSMAX,L
  REAL MAT01(NCOL,LCOL)!,MAT2(NCOL,LCOL)!,VALMAX
  !real*8 time3
  L=LCOL
  
  MAT01=MAT0
  IF(OPT.EQ.1) THEN
     DO I=1,LCOL
        !VALMIN=MINVAL(MAT01(OBJC,1:LCOL))  !MIN VALUE
        POSMIN=MINLOC(MAT01(OBJC,1:L),L) !POSITION MIN VALUE
        MAT0(1:NCOL,I)=MAT01(1:NCOL,POSMIN) !SAVE NEW MATRIX WITH ORDER
        MAT01(1:NCOL,POSMIN)=MAT01(1:NCOL,L)!REPLACE MIN VALUE WITH THE LAST VALUE OF ARRAY
        L=L-1
     END DO
  END IF
  IF(OPT.EQ.2) THEN
     DO I=1,LCOL
        !VALMAX=MAXVAL(MAT01(OBJC,1:LCOL))  !MAX VALUE
        POSMAX=MAXLOC(MAT01(OBJC,1:L),L) !POSITION MAX VALUE
        MAT0(1:NCOL,I)=MAT01(1:NCOL,POSMAX) !SAVE NEW MATRIX WITH ORDER
        MAT01(1:NCOL,POSMAX)=MAT01(1:NCOL,L)!REPLACE MAX VALUE WITH THE LAST VALUE OF ARRAY
        L=L-1
     END DO
  END IF
  !print*,"time for orderori",(OMP_get_wtime()-time3)
     
END SUBROUTINE ORDER

SUBROUTINE CLEANFOLDER()
  IMPLICIT NONE
  logical :: file_exists(10)

  INQUIRE(FILE="lagr.7", EXIST=file_exists(1))
  INQUIRE(FILE="global.30", EXIST=file_exists(2))
  INQUIRE(FILE="Qevol.txt", EXIST=file_exists(3))
  
  IF(file_exists(1).EQV. .TRUE.) CALL SYSTEM("rm lagr.7")
  IF(file_exists(2).EQV. .TRUE.) CALL SYSTEM("rm global.30")
  IF(file_exists(3).EQV. .TRUE.) CALL SYSTEM("rm Qevol.txt")
 
END SUBROUTINE CLEANFOLDER

SUBROUTINE COPYFOLDER(FOLDER1,FOLDER2,VIRF,SECONDSEG,FOLDER3,SECONDRH,SECSEGH,FIMF,FOLDER4,SX2)
  IMPLICIT NONE
  logical :: file_exists(10)
  CHARACTER*300 FOLDER1,FOLDER2,FOLDER3,FOLDER4
  INTEGER VIRF,SECONDSEG,SECONDRH,SECSEGH,FIMF
  INTEGER CONT
  REAL SX2(10)
  INTEGER I

  IF(VIRF.EQ.10) THEN
     PRINT*,"WARNING, I WILL DELETE 2ndgen-2, SHOULD I CONTINUE?=10"
     READ(*,*) CONT
     IF(CONT.NE.10) STOP
  END IF
  INQUIRE(FILE=TRIM(FOLDER2)//"/input", EXIST=file_exists(1))

  IF(file_exists(1).EQV. .TRUE.) THEN
     PRINT*,"DELETING ",TRIM(FOLDER2)
     CALL SYSTEM("rm -r "//TRIM(FOLDER2))
  END IF
  CALL SYSTEM("cp -r "//TRIM(FOLDER1)//" "//TRIM(FOLDER2))
  IF(SECONDSEG.EQ.2) CALL SYSTEM("cp "//TRIM(FOLDER3)//"/cluster_M*_1.txt "//TRIM(FOLDER2))
  IF(SECONDSEG.EQ.2) PRINT*,"COPYING",TRIM(FOLDER3),"/cluster_M*_1.txt TO ",TRIM(FOLDER2) !NOSEG IN SEG
  
  IF(SECONDRH.GT.0.OR.SECSEGH.GT.0.OR.FIMF.GT.0) THEN
     PRINT*,"COPYING",TRIM(FOLDER3),"/cluster_M*_1.txt TO ",TRIM(FOLDER2) !RH=1.0,HIGHSEG,FULLIMF
     CALL SYSTEM("cp "//TRIM(FOLDER3)//"/cluster_M*_1.txt "//TRIM(FOLDER2))
     OPEN(11,FILE=TRIM(FOLDER4)//"/SX.dat",STATUS="OLD")
     DO I=1,10
        READ(11,*) SX2(I)
     END DO
  END IF
  
END SUBROUTINE COPYFOLDER

SUBROUTINE SCALING(MAV,NPART,SX,TSX,VSX)
  IMPLICIT NONE
  INTEGER NPART
  REAL MAV,SX,TSX,VSX

  REAL TWOPI,GM,AU,PC,TSTAR,VSTAR

  TWOPI = 8.0D0*ATAN(1.0D0)
  GM = 1.32712442099D+26
  AU = 1.49597870700D+13
  PC = 1296000.0D0/TWOPI*AU !3.0856776e+18

  TSTAR = SQRT(PC/GM)*PC
  TSTAR = TSTAR/(3.15576D+07*1.0D+06)
  TSX = TSTAR*SQRT(SX**3/((MAV*NPART)))

  VSTAR = 1.0D-05*SQRT(GM/PC)
  VSX = VSTAR*SQRT(((MAV*NPART)/SX))
END SUBROUTINE SCALING

SUBROUTINE COPYCLUSTERS(OPT,WORKFOLDER,SIMF,SIMICHAR,HOME,SFE,SEG,MC,MCLUSTER,SFESCHAR,SFES,MCLUSTER2,HOME2)
  IMPLICIT NONE
  INTEGER SIMF,SFE,SEG,MC,SFES(2)
  REAL MCLUSTER,MCLUSTER2
  CHARACTER*20 OPT(6)
  CHARACTER*50 HOME
  CHARACTER*300 WORKFOLDER,SIMICHAR(3,10),SFESCHAR(3),HOME2
  CHARACTER*2 CLUSTERCHAR
  logical :: file_exists(10)

  INTEGER I,J,K,I2,CONT
  CHARACTER*300 PATHSIMBASE,MCLUSTERCHAR,MCLUSTERCHAR2
  
  PATHSIMBASE=TRIM(HOME2)//"sim_WF_paper/sim_R136/sim_M6_rhoUniform_paper/rho10000/SFE0.15/SEG/"
  INQUIRE(FILE='sim_base', EXIST=file_exists(1))
  IF(file_exists(1).EQV. .TRUE.) CALL SYSTEM("rm -r sim_base")
  CALL SYSTEM('cp -r '//TRIM(PATHSIMBASE)//'sim_base ./')
  INQUIRE(FILE='sim_base', EXIST=file_exists(1))
  IF(file_exists(1).EQV. .FALSE.) THEN
     PRINT*,"sim_base NOT FOUND, CHANGE PATHSIMBASE IN COPYCLUSTERS SUBROUTINE"
     STOP
  END IF
  
  IF(MCLUSTER.LT.1000) WRITE(MCLUSTERCHAR,12) INT(MCLUSTER)
  IF(MCLUSTER.GE.1000.AND.MCLUSTER.LT.10000) WRITE(MCLUSTERCHAR,13) INT(MCLUSTER)
  IF(MCLUSTER.GE.10000.AND.MCLUSTER.LT.100000) WRITE(MCLUSTERCHAR,14) INT(MCLUSTER)
  IF(MCLUSTER.GE.100000.AND.MCLUSTER.LT.1000000) WRITE(MCLUSTERCHAR,15) INT(MCLUSTER)

  IF((MC.EQ.4.OR.MC.EQ.5)) THEN
     IF(MCLUSTER2.LT.1000) WRITE(MCLUSTERCHAR2,12) INT(MCLUSTER2)
     IF(MCLUSTER2.GE.1000.AND.MCLUSTER2.LT.10000) WRITE(MCLUSTERCHAR2,13) INT(MCLUSTER2)
     IF(MCLUSTER2.GE.10000.AND.MCLUSTER2.LT.100000) WRITE(MCLUSTERCHAR2,14) INT(MCLUSTER2)
     IF(MCLUSTER2.GE.100000.AND.MCLUSTER2.LT.1000000) WRITE(MCLUSTERCHAR2,15) INT(MCLUSTER2)
  END IF
  
  OPEN(101,FILE="copyall.sh",STATUS="REPLACE")
  WRITE(101,*) "rm -r sim_1 sim_2 sim_3 sim_4 sim_5"
  WRITE(101,*) "rm *~"
  WRITE(101,*) "mkdir sim_1 sim_2 sim_3 sim_4 sim_5"
  DO J=1,2
     IF(J.EQ.1) K=1
     IF(J.EQ.2) K=3
     DO I=1,SIMF
        WRITE(101,*) "cp -r sim_base/ .",TRIM(SIMICHAR(K,I))
     END DO
  END DO
 
  WRITE(101,*) ""
  IF(MC.EQ.4.OR.MC.EQ.5) THEN
     PRINT*,"COPYING 1ST CLUSTERS FROM ",TRIM(HOME2),"cluster/",TRIM(OPT(6)),"/",TRIM(OPT(5)),"/",TRIM(SFESCHAR(1))
     PRINT*,"COPYING 2ND CLUSTERS FROM ",TRIM(HOME2),"cluster/",TRIM(OPT(6)),"/",TRIM(OPT(5)),"/",TRIM(SFESCHAR(2))
  ELSE
     PRINT*,"COPYING CLUSTERS FROM ",TRIM(HOME2),"cluster/",TRIM(OPT(6)),"/",TRIM(OPT(5)),"/",TRIM(OPT(4))
  END IF
  PRINT*,"SHOULD I CONTINUE? YES=1, NO=0"
  READ(*,*) CONT
  IF(CONT.EQ.0) STOP
  IF(MC.EQ.4.OR.MC.EQ.5) OPT(4)=SFESCHAR(1)
  DO I=1,10
     I2=I
     IF(I.LE.SIMF) J=1
     IF(I.GT.SIMF) THEN
        J=3
        I2=I2-SIMF
        IF(MC.EQ.4.OR.MC.EQ.5) THEN
           OPT(4)=SFESCHAR(2)
           MCLUSTERCHAR=MCLUSTERCHAR2
        END IF
     END IF
     IF(I.LT.10)  WRITE(CLUSTERCHAR,10) I
     IF(I.GE.10)  WRITE(CLUSTERCHAR,11) I
     WRITE(101,*) "cp ",TRIM(HOME2),"cluster/",TRIM(OPT(6)),"/",TRIM(OPT(5)),"/",TRIM(OPT(4)),&
          "/c",TRIM(CLUSTERCHAR),"/cluster_M",TRIM(MCLUSTERCHAR),".00_1.txt .",TRIM(SIMICHAR(J,I2))
  END DO
  WRITE(101,*) ""
  WRITE(101,*) "cp ",TRIM(HOME2),"cluster/",TRIM(OPT(6)),"/",TRIM(OPT(5)),"/",TRIM(SFESCHAR(1)),&
          "/SX.dat"," ./"
  CLOSE(101)
  CALL SYSTEM("sh copyall.sh")
  
10 FORMAT(I1)
11 FORMAT(I2)
12 FORMAT(I3)
13 FORMAT(I4)
14 FORMAT(I5)
15 FORMAT(I6)
  
END SUBROUTINE COPYCLUSTERS

SUBROUTINE WAITINGFORRUNING(OPT,SFESCHAR)
  IMPLICIT NONE
  CHARACTER*20 OPT(6)
  CHARACTER*300 SFESCHAR(3),COMMAND1,COMMAND2,COMMAND3,COMMAND4
  INTEGER NSIM,MAXSIM
  integer i

  COMMAND1="ps aux | grep ""nbody"" | awk {'print ""ls -l /proc/"
  COMMAND1=TRIM(COMMAND1)//'"$2"'
  COMMAND1=TRIM(COMMAND1)//"/cwd""'}>temp.sh"
1 CALL SYSTEM(COMMAND1)
  COMMAND2='sh temp.sh | grep "'//TRIM(OPT(3))//'/'//TRIM(SFESCHAR(3))//'/'//TRIM(OPT(5))//'" > sims.dat'
  CALL SYSTEM(COMMAND2)
  COMMAND3='wc -l sims.dat > lines.dat'
  CALL SYSTEM(COMMAND3)
  OPEN(111,FILE='lines.dat',STATUS='OLD')
  READ(111,*) NSIM
  CLOSE(111)
  MAXSIM=0
  
  IF(NSIM.GE.1) THEN
     PRINT*,NSIM,"SIMULATIONS RUNNING, WAITING UNTIL THEY ARE DONE"
     PRINT*,"GPU USING"
     CALL SYSTEM('echo $CUDA_VISIBLE_DEVICES')
     PRINT*,TRIM(OPT(3))//'/'//TRIM(SFESCHAR(3))//'/'//TRIM(OPT(5))
     CALL SLEEP(1800)
     GOTO 1
  ELSE
     RETURN
  END IF
  

END SUBROUTINE WAITINGFORRUNING
